### ISSUE TITLE
Timetable Admin-Internet Explorer doesnt update the changes on screen..

### ISSUE THREAD

**Issue by ak883** [CUL-DigitalServices/grasshopper-ui#441] opened 2015-05-28 09:25 UTC
this happens when user tries to

adding new(module or series) 
borrow series 
add events
edit events

I can see the changes when I clear the cache

Browser -Internet Explorer 11v/ OS Windows 7

**Comment by bp323** [comment] 2015-05-28 12:03
Assigning to myself to have a look

**Comment by bp323** [comment] 2015-05-28 12:11
I have tested in IE9 and IE11 as well as Chrome and cannot reproduce any of the issues you are seeing. Can you make sure QA0 or QA1 is used and you start from a clean cache? Closing.

**Closed by bp323** 2015-05-28 12:11 UTC
Labels: High Priority, In Progress, To Fix

**Comment by ak883** [comment] 2015-05-28 13:06
@bp323 -I have start from a clean cache in IE11v ,created a new module and it worked fine. But when I created the new module again ,it is not working ..  it only works when I start from a clean cache for each case.
