### ISSUE TITLE
Timetable Administration (Add Events)- event disappears when I add event to module, save it and refresh the page

### ISSUE THREAD

**Issue by ak883** [CUL-DigitalServices/grasshopper-ui#409] opened 2015-05-15 09:30 UTC
event disappears form when I add an event to module, save it and refresh the page or I navigate to another page and come back to that page to view the event , this works fine in other browser

ALSO NOTICED WHEN A NEW SERIES IS ADDED TO THE MODULE IT DOESNT APPEAR IN THE LIST 

SCREENSHOT ATTACCHED

Browser  IE 11v Windows 7 professional

![add module-new series](https://cloud.githubusercontent.com/assets/12182828/7650319/0887b58c-faed-11e4-9904-79ced797346d.JPG)

**Comment by bp323** [comment] 2015-05-18 10:56
Cannot reproduce this issue on the latest QA servers. Closing

**Closed by bp323** 2015-05-18 10:56 UTC
Labels: High Priority
